### ISSUE TITLE
Mirroring

### ISSUE THREAD

**Issue by mys007** [oskyhn/CNNs-Without-Borders#5]
Hi, thanks for such a great paper with source code. I'm interested whether you have looked into mirror-padding too? Naively, I would expect that it should perform as S-Conv Circ but without the wrapping/semantic artifacts (the same values appear, just on the "right side" of the image)?

**Comment by oskyhn** [comment]
Hi, thank you for your good comments. 
I could not understand it exactly from your question, which method could perform as SConv-Circ with mirror padding? If the method is SConv-Reflect for Red-Green experiment, the performance on 'Similar testset' becomes even better and on 'Dissimilar testset' it becomes worse, because by mirror padding, the network can learn the location of the objects (in this case boxes) easier especially if the object is closer to the border. It holds for replication padding as well.

**Comment by mys007** [comment]
Hi, thanks for the answer. I've meant `padding_mode='reflect'` instead of `'circular'` (in PyTorch notation)...

**Comment by oskyhn** [comment]
If your question is clearly answered, then I will close the issue.

**Comment by mys007** [comment]
Em, I think it's not. But I can also try it myself:).
